services:
  web:
    build:
      context: .
      args:
        VERSION: ${APP_VERSION:-0.1.0}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      APP_VERSION: ${APP_VERSION:-0.1.0}
